### ISSUE TITLE
Are you using opencl to run on fpga ?

### ISSUE THREAD

**Issue by Thilanka97** [zlmo/Object-detection-based-on-darknet-and-FPGA#1]
This looks interesting ! You are trying to run YOLO on fpga right ? Are you using openCL for this ? Are you using cuda also ? I thought that you can not use cuda with FPGAs.

**Comment by Thilanka97** [comment]
@zlmo could you please explain how you implemented yolo on fpga ? Because I am able to read the pdf file since it is not in English. or could you please upload a pdf file which is explained in english ? 

Thanks in advance!

**Comment by Thilanka97** [comment]
@zlmo what does "gemm_nn_opencl.cl files do ? dont you need to write all the kernel codes and host codes in opencl ?

**Comment by zlmo** [comment]
@Thilanka97 Hi, yes, I am trying to implement YOLO on fpga, but this project is just beginning. I am using openCL to accelerate YOLO, but with the cpu-version of  Darknet. I have writed a simple kernel for the convolutional layer, but the kernel had some problem and I still can't get the right prediction.
In this project, the FPGA card which I use supporting PCIe. I writed a kernel file to repace the original Matrix multiplication in gemm_nn.c(maybe this file, I've forgot...), and writed a host file(/src/gemm_fpga.cpp) for this kernel, and added these files to Darknet. Also, I made some changes in Makefile to compile these new openCL files.
I could complie Darknet successfully, but can't get the right result. So I am still trying on it and I think this way is feasible.
And FPGA dosen't support cuda, but if you have a GPU card and a FPGA card in one machine(needs two PCIe port), I think you could complie with cuda and openCL together in Darknet, which I will try in future to realise heterogeneous computing.
Any question, please contact me!

**Comment by Thilanka97** [comment]
@zlmo by writing and replacing only the matrix multiplication file is enough to run on fpga without gpu ? I am confused ! were you able to run yolo with this on fpga (without gpu) ?

**Comment by Thilanka97** [comment]
@zlmo  heyy and do u have any idea of how different is coding for fpga using opencl and coding for gpu using fpga ?

**Comment by zlmo** [comment]
@Thilanka97 Hi, I have written an English version of the pdf file, I hope it will help.

**Comment by Thilanka97** [comment]
@zlmo heyy thank you so much for the english version of your pdf. I went through the file. So are you using the fpga only to do/run the ,matrix multiplications in the conv layers?  for the rest of the operation s and processing you use the host ? 

Thanks in advance!

**Comment by zlmo** [comment]
@Thilanka97 Yes, I am still not so familiar with openCL for now and this is an attempt for running yolo on fpga. So I just write a kernel for the conv layers, the rest of the operations are still running on the host. But this attempt mainly aims to verify the feasibility of running Darknet on fpga. In future I may try realize the other compute-intensive operations on fpga. So do you think this way is OK or any advices?

**Comment by Thilanka97** [comment]
@zlmo I am also new to opencl. I am still learning. I think your work is pretty good! keep it up. you should try to implement other kernels in opencl too. Thanks!
